config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/template'

  resources :pie_piece_transaction_splits

  resources :transaction_splits

  resources :transaction_records

  resources :pie_pieces

  resources :pies

  resources :users

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :pies, only: [:index, :create, :update, :destroy]
      resources :pie_pieces, only: [:index, :create, :update, :destroy]
      resources :transaction_splits, only: [:index, :create, :update, :destroy]
    end
  end

   root 'welcome#index'

end

app/models/transaction_split.rb
class TransactionSplit < ActiveRecord::Base
  belongs_to :transaction_record
  has_many :pie_piece_transaction_splits
  has_many :pie_pieces, through: :pie_piece_transaction_splits
  scope :user, ->(id) {
    joins(:transaction_record)
    .where('transaction_records.user_id = ?', id)
  }
end

app/controllers/api/v1/transaction_splits_controller.rb
class Api::V1::TransactionSplitsController < ApplicationController
  def index
    @transaction_splits = TransactionSplit.all.user(get_current_user.id)
  end

  def create
  end

  def update
  end

  def delete
  end
end

app/controllers/transaction_splits_controller.rb
class TransactionSplitsController < ApplicationController
  before_action :set_transaction_split, only: [:show, :edit, :update, :destroy]

  # GET /transaction_splits
  # GET /transaction_splits.json
  def index
    @transaction_splits = TransactionSplit.all
  end

  # GET /transaction_splits/1
  # GET /transaction_splits/1.json
  def show
  end

  # GET /transaction_splits/new
  def new
    @transaction_split = TransactionSplit.new
  end

  # GET /transaction_splits/1/edit
  def edit
  end

  # POST /transaction_splits
  # POST /transaction_splits.json
  def create
    @transaction_split = TransactionSplit.new(transaction_split_params)

    respond_to do |format|
      if @transaction_split.save
        format.html { redirect_to @transaction_split, notice: 'Transaction split was successfully created.' }
        format.json { render :show, status: :created, location: @transaction_split }
      else
        format.html { render :new }
        format.json { render json: @transaction_split.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_splits/1
  # PATCH/PUT /transaction_splits/1.json
  def update
    respond_to do |format|
      if @transaction_split.update(transaction_split_params)
        format.html { redirect_to @transaction_split, notice: 'Transaction split was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction_split }
      else
        format.html { render :edit }
        format.json { render json: @transaction_split.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_splits/1
  # DELETE /transaction_splits/1.json
  def destroy
    @transaction_split.destroy
    respond_to do |format|
      format.html { redirect_to transaction_splits_url, notice: 'Transaction split was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_split
      @transaction_split = TransactionSplit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_split_params
      params.require(:transaction_split).permit(:transaction_record_id, :amount, :description)
    end
end

app/helpers/api/v1/transaction_splits_helper.rb
module Api::V1::TransactionSplitsHelper
end

app/helpers/transaction_splits_helper.rb
module TransactionSplitsHelper
end

app/views/transaction_splits/_form.html.erb
<%= form_for(@transaction_split) do |f| %>
  <% if @transaction_split.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction_split.errors.count, "error") %> prohibited this transaction_split from being saved:</h2>

      <ul>
      <% @transaction_split.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_record_id %><br>
    <%= f.text_field :transaction_record_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaction_splits/edit.html.erb
<h1>Editing transaction_split</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction_split %> |
<%= link_to 'Back', transaction_splits_path %>

app/views/transaction_splits/index.html.erb
<h1>Listing transaction_splits</h1>

<table>
  <thead>
    <tr>
      <th>Transaction record</th>
      <th>Amount</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_splits.each do |transaction_split| %>
      <tr>
        <td><%= transaction_split.transaction_record %></td>
        <td><%= transaction_split.amount %></td>
        <td><%= transaction_split.description %></td>
        <td><%= link_to 'Show', transaction_split %></td>
        <td><%= link_to 'Edit', edit_transaction_split_path(transaction_split) %></td>
        <td><%= link_to 'Destroy', transaction_split, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction split', new_transaction_split_path %>

app/views/transaction_splits/new.html.erb
<h1>New transaction_split</h1>

<%= render 'form' %>

<%= link_to 'Back', transaction_splits_path %>

app/views/transaction_splits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction record:</strong>
  <%= @transaction_split.transaction_record %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction_split.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction_split.description %>
</p>

<%= link_to 'Edit', edit_transaction_split_path(@transaction_split) %> |
<%= link_to 'Back', transaction_splits_path %>