config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/template'

  resources :pie_piece_transaction_splits

  resources :transaction_splits

  resources :transaction_records

  resources :pie_pieces

  resources :pies

  resources :users

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :pies, only: [:index, :create, :update, :destroy]
      resources :pie_pieces, only: [:index, :create, :update, :destroy]
      resources :transaction_splits, only: [:index, :create, :update, :destroy]
    end
  end

   root 'welcome#index'

end

app/controllers/api/v1/pies_controller.rb
class Api::V1::PiesController < ApplicationController
  before_action :set_pie, only: [:update, :destroy]

  def index
    @pies = Pie.all.user(get_current_user.id)
  end

  def create
    @pie = Pie.new(pie_params.merge!(
      :user_id => get_current_user.id
    ))

    if @pie.save
      render json: @pie, status: :created
    else
      render json: @pie.errors, status: :unprocessable_entity
    end
  end

  def update
    if @pie.update(pie_params)
      render json: @pie, status: :ok
    else
      render json: @pie.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @pie.destroy
    head :no_content
  end

  private
    def set_pie
      @pie = Pie.find_by! id: params[:id], user_id: get_current_user.id
    end

    def pie_params
      new_params = params.permit(
        :title,
        :is_required
      )
    end
end

app/controllers/pies_controller.rb
class PiesController < ApplicationController
  before_action :set_py, only: [:show, :edit, :update, :destroy]

  # GET /pies
  # GET /pies.json
  def index
    @pies = Pie.all
  end

  # GET /pies/1
  # GET /pies/1.json
  def show
  end

  # GET /pies/new
  def new
    @py = Pie.new
  end

  # GET /pies/1/edit
  def edit
  end

  # POST /pies
  # POST /pies.json
  def create
    @py = Pie.new(pie_params)

    respond_to do |format|
      if @py.save
        format.html { redirect_to @py, notice: 'Pie was successfully created.' }
        format.json { render :show, status: :created, location: @py }
      else
        format.html { render :new }
        format.json { render json: @py.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pies/1
  # PATCH/PUT /pies/1.json
  def update
    respond_to do |format|
      if @py.update(pie_params)
        format.html { redirect_to @py, notice: 'Pie was successfully updated.' }
        format.json { render :show, status: :ok, location: @py }
      else
        format.html { render :edit }
        format.json { render json: @py.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pies/1
  # DELETE /pies/1.json
  def destroy
    @py.destroy
    respond_to do |format|
      format.html { redirect_to pies_url, notice: 'Pie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_py
      @py = Pie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pie_params
      params.require(:pie).permit(:user_id, :title, :is_required)
    end
end

app/helpers/api/v1/pies_helper.rb
module Api::V1::PiesHelper
end

app/helpers/pies_helper.rb
module PiesHelper
end

app/views/pies/_form.html.erb
<%= form_for(@py) do |f| %>
  <% if @py.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@py.errors.count, "error") %> prohibited this py from being saved:</h2>

      <ul>
      <% @py.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :is_required %><br>
    <%= f.check_box :is_required %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pies/edit.html.erb
<h1>Editing py</h1>

<%= render 'form' %>

<%= link_to 'Show', @py %> |
<%= link_to 'Back', pies_path %>

app/views/pies/index.html.erb
<h1>Listing pies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Is required</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pies.each do |py| %>
      <tr>
        <td><%= py.user %></td>
        <td><%= py.title %></td>
        <td><%= py.is_required %></td>
        <td><%= link_to 'Show', py %></td>
        <td><%= link_to 'Edit', edit_py_path(py) %></td>
        <td><%= link_to 'Destroy', py, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pie', new_py_path %>

app/views/pies/new.html.erb
<h1>New py</h1>

<%= render 'form' %>

<%= link_to 'Back', pies_path %>

app/views/pies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @py.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @py.title %>
</p>

<p>
  <strong>Is required:</strong>
  <%= @py.is_required %>
</p>

<%= link_to 'Edit', edit_py_path(@py) %> |
<%= link_to 'Back', pies_path %>