config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/template'

  resources :pie_piece_transaction_splits

  resources :transaction_splits

  resources :transaction_records

  resources :pie_pieces

  resources :pies

  resources :users

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :pies, only: [:index, :create, :update, :destroy]
      resources :pie_pieces, only: [:index, :create, :update, :destroy]
      resources :transaction_splits, only: [:index, :create, :update, :destroy]
    end
  end

   root 'welcome#index'

end

app/models/pie_piece_transaction_split.rb
class PiePieceTransactionSplit < ActiveRecord::Base
  belongs_to :pie
  belongs_to :pie_piece
  belongs_to :transaction_split
end

app/controllers/pie_piece_transaction_splits_controller.rb
class PiePieceTransactionSplitsController < ApplicationController
  before_action :set_pie_piece_transaction_split, only: [:show, :edit, :update, :destroy]

  # GET /pie_piece_transaction_splits
  # GET /pie_piece_transaction_splits.json
  def index
    @pie_piece_transaction_splits = PiePieceTransactionSplit.all
  end

  # GET /pie_piece_transaction_splits/1
  # GET /pie_piece_transaction_splits/1.json
  def show
  end

  # GET /pie_piece_transaction_splits/new
  def new
    @pie_piece_transaction_split = PiePieceTransactionSplit.new
  end

  # GET /pie_piece_transaction_splits/1/edit
  def edit
  end

  # POST /pie_piece_transaction_splits
  # POST /pie_piece_transaction_splits.json
  def create
    @pie_piece_transaction_split = PiePieceTransactionSplit.new(pie_piece_transaction_split_params)

    respond_to do |format|
      if @pie_piece_transaction_split.save
        format.html { redirect_to @pie_piece_transaction_split, notice: 'Pie piece transaction split was successfully created.' }
        format.json { render :show, status: :created, location: @pie_piece_transaction_split }
      else
        format.html { render :new }
        format.json { render json: @pie_piece_transaction_split.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pie_piece_transaction_splits/1
  # PATCH/PUT /pie_piece_transaction_splits/1.json
  def update
    respond_to do |format|
      if @pie_piece_transaction_split.update(pie_piece_transaction_split_params)
        format.html { redirect_to @pie_piece_transaction_split, notice: 'Pie piece transaction split was successfully updated.' }
        format.json { render :show, status: :ok, location: @pie_piece_transaction_split }
      else
        format.html { render :edit }
        format.json { render json: @pie_piece_transaction_split.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pie_piece_transaction_splits/1
  # DELETE /pie_piece_transaction_splits/1.json
  def destroy
    @pie_piece_transaction_split.destroy
    respond_to do |format|
      format.html { redirect_to pie_piece_transaction_splits_url, notice: 'Pie piece transaction split was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pie_piece_transaction_split
      @pie_piece_transaction_split = PiePieceTransactionSplit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pie_piece_transaction_split_params
      params.require(:pie_piece_transaction_split).permit(:pie_id, :pie_piece_id, :transaction_split_id)
    end
end

app/helpers/pie_piece_transaction_splits_helper.rb
module PiePieceTransactionSplitsHelper
end

app/views/pie_piece_transaction_splits/_form.html.erb
<%= form_for(@pie_piece_transaction_split) do |f| %>
  <% if @pie_piece_transaction_split.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pie_piece_transaction_split.errors.count, "error") %> prohibited this pie_piece_transaction_split from being saved:</h2>

      <ul>
      <% @pie_piece_transaction_split.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pie_id %><br>
    <%= f.text_field :pie_id %>
  </div>
  <div class="field">
    <%= f.label :pie_piece_id %><br>
    <%= f.text_field :pie_piece_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_split_id %><br>
    <%= f.text_field :transaction_split_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pie_piece_transaction_splits/edit.html.erb
<h1>Editing pie_piece_transaction_split</h1>

<%= render 'form' %>

<%= link_to 'Show', @pie_piece_transaction_split %> |
<%= link_to 'Back', pie_piece_transaction_splits_path %>

app/views/pie_piece_transaction_splits/index.html.erb
<h1>Listing pie_piece_transaction_splits</h1>

<table>
  <thead>
    <tr>
      <th>Pie</th>
      <th>Pie piece</th>
      <th>Transaction split</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pie_piece_transaction_splits.each do |pie_piece_transaction_split| %>
      <tr>
        <td><%= pie_piece_transaction_split.pie %></td>
        <td><%= pie_piece_transaction_split.pie_piece %></td>
        <td><%= pie_piece_transaction_split.transaction_split %></td>
        <td><%= link_to 'Show', pie_piece_transaction_split %></td>
        <td><%= link_to 'Edit', edit_pie_piece_transaction_split_path(pie_piece_transaction_split) %></td>
        <td><%= link_to 'Destroy', pie_piece_transaction_split, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pie piece transaction split', new_pie_piece_transaction_split_path %>

app/views/pie_piece_transaction_splits/new.html.erb
<h1>New pie_piece_transaction_split</h1>

<%= render 'form' %>

<%= link_to 'Back', pie_piece_transaction_splits_path %>

app/views/pie_piece_transaction_splits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pie:</strong>
  <%= @pie_piece_transaction_split.pie %>
</p>

<p>
  <strong>Pie piece:</strong>
  <%= @pie_piece_transaction_split.pie_piece %>
</p>

<p>
  <strong>Transaction split:</strong>
  <%= @pie_piece_transaction_split.transaction_split %>
</p>

<%= link_to 'Edit', edit_pie_piece_transaction_split_path(@pie_piece_transaction_split) %> |
<%= link_to 'Back', pie_piece_transaction_splits_path %>